version: '3'
services:
  floatev-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 9805:8100
    extra_hosts:
      - backend.wrenchboard.api.live:10.10.33.15
      - backend.wrenchboard.api.test:10.10.33.15
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
       - ./:/www/app
    tty: true
    stdin_open: true
    working_dir: /www/app
    # command: ionic serve --external
volumes:
  src: